return {
    autoreload = false,
    screenblur = true,
    keys = { 'F2', 'K', 'TAB' },
    enablekeys = { 249 },
    aimedfiring = false,
    giveplayerlist = false,
    weaponanims = true,
    itemnotify = true,
    weaponnotify = true,
    imagepath = 'nui://ox_inventory/web/images',
    dropprops = false,
    dropmodel = 'prop_med_bag_01b',
    weaponmismatch = true,
    ignoreweapons = {},
    suppresspickups = true,
    disableweapons = false,
    disablesetupnotification = false,
    enablestealcommand = true,
}
